title: Add a gradient
hero_image: images/banner.png
description: Add a gradient to an element in HTML.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Add a gradient
