title: Ajouter un dégradé
hero_image: images/banner.png
description: Ajoute un dégradé à un élément en HTML.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter un dégradé
